# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ubuntu-master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'
      - name: Build with Maven
        env:
          TARANTOOL_SERVER_USER: root
          TARANTOOL_SERVER_GROUP: root
        run: mvn -e -B verify --file pom.xml

      - name: Run enterprise tests
        env:
          TARANTOOL_SERVER_USER: root
          TARANTOOL_SERVER_GROUP: root
          DOWNLOAD_SDK_URI: ${{ secrets.DOWNLOAD_SDK_URI }}
          SDK_VERSION: tarantool-enterprise-sdk-nogc64-2.10.7-0-r563.linux.x86_64
        run: mvn -B test -P enterprise --file pom.xml
